#cloud-config
package_update: true
package_upgrade: true
packages:
  - ca-certificates
  - curl
  - apt-transport-https
  - gnupg
  - lsb-release

users:
  - default
  - name: devops
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    shell: /bin/bash
    groups: sudo


runcmd:
  - |
      set -e
      mkdir -p /home/devops

      cat <<'EOF' > /home/devops/kind-config.yaml
      kind: Cluster
      apiVersion: kind.x-k8s.io/v1alpha4
      nodes:
        - role: control-plane
        - role: worker
        - role: worker
      EOF

      export DEBIAN_FRONTEND=noninteractive

      echo "📦 Installing Docker"
      apt-get update -y
      apt-get install -y docker.io

      systemctl enable docker
      systemctl start docker

      echo "⏳ Waiting for Docker to be ready"
      until docker info >/dev/null 2>&1; do
        sleep 2
      done

      echo "👤 Adding devops user to docker group"
      groupadd -f docker
      usermod -aG docker devops

      echo "📦 Installing kubectl"
      curl -fsSL "https://dl.k8s.io/release/$(curl -fsSL https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" \
        -o /usr/local/bin/kubectl
      chmod +x /usr/local/bin/kubectl

      echo "📦 Installing helm"
       - curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      echo "📦 Installing kind"
      curl -fsSL https://kind.sigs.k8s.io/dl/v0.22.0/kind-linux-amd64 \
        -o /usr/local/bin/kind
      chmod +x /usr/local/bin/kind

      echo "🚀 Creating kind cluster"
      kind create cluster \
        --name platform-cluster \
        --config /home/devops/kind-config.yaml


final_message: "Cloud-init bootstrap completed successfully"
